# Generated by Django 5.2.12 on 2026-03-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='匹配分数')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='匹配理由')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='items.item', verbose_name='失物招领')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='items.item', verbose_name='寻物启事')),
            ],
            options={
                'verbose_name': '匹配记录',
                'verbose_name_plural': '匹配记录',
                'db_table': 'matches_match',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('found_item', 'lost_item')},
            },
        ),
    ]
