[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:django]
command=gunicorn backend.wsgi:application --bind 127.0.0.1:8000 --workers 2 --timeout 120
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/django.log
stderr_logfile=/var/log/supervisor/django_err.log
environment=DJANGO_SETTINGS_MODULE="backend.settings"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log
