# Generated by Django 5.2.12 on 2026-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('found', '失物招领'), ('lost', '寻物启事')], max_length=10, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('证件', '证件'), ('电子产品', '电子产品'), ('书籍文具', '书籍文具'), ('钥匙', '钥匙'), ('钱包', '钱包'), ('衣物', '衣物'), ('其他', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(verbose_name='描述')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('happened_at', models.DateTimeField(verbose_name='发生时间')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contact_wechat', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信号')),
                ('status', models.CharField(choices=[('active', '进行中'), ('matched', '已匹配'), ('closed', '已关闭')], default='active', max_length=10, verbose_name='状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'db_table': 'items_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', verbose_name='图片')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '物品图片',
                'verbose_name_plural': '物品图片',
                'db_table': 'items_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'items_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
